# HLint configuration file
##########################

- functions:
  - {name: head, within: []} # head can only appear in no modules
  - {name: tail, within: []} 
  - {name: Maybe.fromJust, within: []} 

- ignore: {name: "Use foldl"}
- ignore: {name: "Avoid lambda"} 
- ignore: {name: "Use head"}
- ignore: {name: "Use guards"}
- ignore: {name: "Reduce duplication"}

